/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player.index'
import { Route as PlayerRelationsRouteImport } from './routes/player.relations'
import { Route as PlayerNotesRouteImport } from './routes/player.notes'
import { Route as PlayerChatRouteImport } from './routes/player.chat'
import { Route as PlayerRelationsIdRouteImport } from './routes/player.relations.$id'

const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerRelationsRoute = PlayerRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerNotesRoute = PlayerNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerChatRoute = PlayerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerRelationsIdRoute = PlayerRelationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlayerRelationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/player/chat': typeof PlayerChatRoute
  '/player/notes': typeof PlayerNotesRoute
  '/player/relations': typeof PlayerRelationsRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/player/relations/$id': typeof PlayerRelationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player/chat': typeof PlayerChatRoute
  '/player/notes': typeof PlayerNotesRoute
  '/player/relations': typeof PlayerRelationsRouteWithChildren
  '/player': typeof PlayerIndexRoute
  '/player/relations/$id': typeof PlayerRelationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/player/chat': typeof PlayerChatRoute
  '/player/notes': typeof PlayerNotesRoute
  '/player/relations': typeof PlayerRelationsRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/player/relations/$id': typeof PlayerRelationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/player'
    | '/player/chat'
    | '/player/notes'
    | '/player/relations'
    | '/player/'
    | '/player/relations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/player/chat'
    | '/player/notes'
    | '/player/relations'
    | '/player'
    | '/player/relations/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/player'
    | '/player/chat'
    | '/player/notes'
    | '/player/relations'
    | '/player/'
    | '/player/relations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/relations': {
      id: '/player/relations'
      path: '/relations'
      fullPath: '/player/relations'
      preLoaderRoute: typeof PlayerRelationsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/notes': {
      id: '/player/notes'
      path: '/notes'
      fullPath: '/player/notes'
      preLoaderRoute: typeof PlayerNotesRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/chat': {
      id: '/player/chat'
      path: '/chat'
      fullPath: '/player/chat'
      preLoaderRoute: typeof PlayerChatRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/relations/$id': {
      id: '/player/relations/$id'
      path: '/$id'
      fullPath: '/player/relations/$id'
      preLoaderRoute: typeof PlayerRelationsIdRouteImport
      parentRoute: typeof PlayerRelationsRoute
    }
  }
}

interface PlayerRelationsRouteChildren {
  PlayerRelationsIdRoute: typeof PlayerRelationsIdRoute
}

const PlayerRelationsRouteChildren: PlayerRelationsRouteChildren = {
  PlayerRelationsIdRoute: PlayerRelationsIdRoute,
}

const PlayerRelationsRouteWithChildren = PlayerRelationsRoute._addFileChildren(
  PlayerRelationsRouteChildren,
)

interface PlayerRouteChildren {
  PlayerChatRoute: typeof PlayerChatRoute
  PlayerNotesRoute: typeof PlayerNotesRoute
  PlayerRelationsRoute: typeof PlayerRelationsRouteWithChildren
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerChatRoute: PlayerChatRoute,
  PlayerNotesRoute: PlayerNotesRoute,
  PlayerRelationsRoute: PlayerRelationsRouteWithChildren,
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
